### DISCUSSION TITLE
I would like to ask for a sample configuration file.

### DISCUSSION THREAD

**Discussion by ddd75a650fee04c0ce576c877521c6bd** [igor-petruk/oatbar#21] [General]
Please.

**Comment by mikesimps** [comment]
Here is mine. Hope it helps.

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/564769e4-b883-4643-bdb3-75259b36f0eb" />


```toml
[[bar]]
monitor = "DisplayPort-1"
height = 48
position = "top"
blocks_left = ["workspace", "R", "gap", "L", "music", "R"]
blocks_center = ["L", "weather", "clock", "R"]
blocks_right = [
  "L",
  "volume",
  "cpu",
  "memory",
  "network",
  "disk_used",
  "screen_brightness",
  "R",
  "gap",
  "L",
  "updates_alert",
  "privacy_mic",
  "privacy_webcam",
  "space",
]
margin = { top = 20, bottom = 10 }
background = "#00000000"

[[default_block]]
font = "JetBrainsMono Nerd Font 22"
background = "${base}"
foreground = "${text}"

[[block]]
name = 'L'
type = 'text'
separator_type = 'left'
separator_radius = 15.0

[[block]]
name = 'R'
type = 'text'
separator_type = 'right'
separator_radius = 15.0

[[block]]
name = 'gap'
type = 'text'
separator_type = 'gap'
value = " "
background = "#00000000"

[[block]]
name = 'space'
type = 'text'
separator_type = 'gap'
value = " "

# Generic Persistent Bar Services
[[command]]
name = "stats"
command = "oatbar-stats"

[[command]]
name = "desktop"
command = "oatbar-desktop 2>/dev/null"

[[command]]
name = "i3status"
command = "i3status"

# Left Modules #####################################

[[block]]
name = 'workspace'
type = 'enum'
active = '${desktop:workspace.active}'
variants = '${desktop:workspace.variants}'
foreground = "${crust}"
active_foreground = '${lavender}'
padding = 20
on_mouse_left = "oatbar-desktop $BLOCK_INDEX"
replace = [
  ["1", ""], #work
  ["2", ""], #personal
  ["3", "󰜫"], #webdev
  ["9", ""], #music player
]

[[command]]
name = "player_info"
command = "~/.scripts/bar_player_status.sh 2>/dev/null"
line_names = ["status", "title", "artist", "album"]
once = true

[[block]]
name = 'music'
type = 'text'
value = '${player_info:artist} - ${player_info:title}'
output_format = '󰎇 ${value}'
font = 'Exo2 Medium 18'
show_if_matches = [['${player_info:status}', 'playing']]
pango_markup = false

# Center Modules #####################################

[[command]]
name = "clock"
command = "date '+%a %b %e %H:%M'"
interval = 1

[[block]]
name = 'clock'
type = 'text'
value = '${clock:value}'
foreground = '${text}'
font = "Exo2 Medium 22"

[[command]]
name = "wttrbar"
command = "wttrbar --fahrenheit | jq -r .text 2>/dev/null"
interval = 3600

[[block]]
name = "weather"
type = "text"
value = "${wttrbar:value}"
foreground = '${text}'
font = "Exo2 Medium 22"

# Right Modules #####################################

[[var]] # set default so mute and 0% volume are handled the same
name = "volume"
value = "${i3status:volume.default.Master.0.full_text|def:0}"

[[block]]
name = "volume"
type = "number"
min_value = "0"
max_value = "200"
number_type = "percent"
value = "${volume}"
foreground = "${sky}"
number_display = "text"
padding = 20
on_mouse_left = "flatpak run com.saivert.pwvucontrol"
ramp = [["0", " "], ["10", "  ${value}"], ["70", "  ${value}"]]

[[block]]
name = "cpu"
type = "text"
value = " ${stats:cpu.percent|align: >2}%"
foreground = "${sapphire}"
padding = 20
on_mouse_left = "alacritty -e btop"

[[block]]
name = "memory"
type = "text"
value = " ${stats:memory.percent}%"
foreground = "${blue}"
padding = 20

[[command]]
name = "mbps"
command = "oatctl --instance-name=mybar var get stats:net.enp1s0.rx_per_sec | xargs ~/.scripts/bar_bps_to_mbps.sh"
interval = 3

[[block]]
name = "network"
type = "number"
number_type = "number"
min_value = "0"
value = "${mbps:value|def:0}"
output_format = "󰱦 ${value|align: ^3}<span font='JetBrainsMono Nerd Font 8'>Mbps</span>"
foreground = "${lavender}"
padding = 10
on_mouse_left = "alacritty -e nmtui"

[[block]]
name = 'disk_used'
type = 'number'
number_type = "percent"
value = '${i3status:disk_info./.full_text}'
output_format = '󰋊 ${value}'
foreground = "${text}"
padding = 20
on_mouse_left = "filelight"

[[command]]
name = "screen_brightness"
command = "~/.scripts/bar_brightness.sh | jq .percentage 2>/dev/null"
interval = 60

[[block]]
name = "screen_brightness"
type = "number"
number_type = "percent"
min_value = "0"
max_value = "100"
value = "${screen_brightness:value}"
output_format = "${value}"
foreground = "${subtext0}"
on_mouse_left = 'ddcutil setvcp 10 30 2>/dev/null'
on_mouse_middle = 'ddcutil setvcp 10 70 2>/dev/null'
on_mouse_right = 'ddcutil setvcp 10 90 2>/dev/null'
ramp = [["0", "󰃞 ${value}"], ["50", "󰃟 ${value}"], ["90", "󰃠 ${value}"]]

# Use this command to identify active sound sources when using mic:
# find /proc/asound -name status -exec grep -v closed {} +i
[[command]]
name = "privacy_mic_status"
command = "cat /proc/asound/card2/pcm0c/sub0/status | grep ':' | cut -d ':' -f 2- | sed 's/^ *//' | head -n 1"
interval = 2

# Displays when mic is being used
[[block]]
name = 'privacy_mic'
type = 'text'
value = ''
output_format = ''
show_if_matches = [['${privacy_mic_status:value}', 'RUNNING']]
background = '${red}'
foreground = '${mantle}'
padding = 10

# Use this command to identify active sound sources when using mic:
# find /proc/asound -name status -exec grep -v closed {} +i
[[command]]
name = "privacy_webcam_status"
command = "fuser /dev/video0 >/dev/null 2>&1 && echo 'yes' || echo 'no'"
interval = 2

# Displays when webcam is being used
[[block]]
name = 'privacy_webcam'
type = 'text'
value = ''
output_format = '󰖠'
show_if_matches = [['${privacy_webcam_status:value}', 'yes']]
background = '${red}'
foreground = '${mantle}'
padding = 10

# Check for updates (does not check AUR)
[[command]]
name = "updates"
command = "checkupdates > /dev/null 2>&1 && echo 'yes' || echo 'no'"
interval = 14400                                                     # every 4 hours

# Displays when webcam is being used
[[block]]
name = 'updates_alert'
type = 'text'
value = ''
output_format = ''
show_if_matches = [['${updates:value}', 'yes']]
font = "Symbols Nerd Font Mono 22"
background = '${green}'
foreground = '${overlay0}'
padding = 10
on_mouse_left = "alacritty -e yay && oatctl --instance-name=mybar var set updates:value no"

# Cattpuccin Frappe
[[var]]
name = "base"
value = "#303446"
[[var]]
name = "mantle"
value = "#292c3c"
[[var]]
name = "crust"
value = "#232634"
[[var]]
name = "text"
value = "#c6d0f5"
[[var]]
name = "subtext0"
value = "#a5adce"
[[var]]
name = "subtext1"
value = "#b5bfe2"
[[var]]
name = "surface0"
value = "#414559"
[[var]]
name = "surface1"
value = "#51576d"
[[var]]
name = "surface2"
value = "#626880"
[[var]]
name = "overlay0"
value = "#737994"
[[var]]
name = "overlay1"
value = "#838ba7"
[[var]]
name = "overlay2"
value = "#949cbb"
[[var]]
name = "blue"
value = "#8caaee"
[[var]]
name = "lavender"
value = "#babbf1"
[[var]]
name = "sapphire"
value = "#85c1dc"
[[var]]
name = "sky"
value = "#99d1db"
[[var]]
name = "teal"
value = "#81c8be"
[[var]]
name = "green"
value = "#a6d189"
[[var]]
name = "yellow"
value = "#e5c890"
[[var]]
name = "peach"
value = "#ef9f76"
[[var]]
name = "maroon"
value = "#ea999c"
[[var]]
name = "red"
value = "#e78284"
[[var]]
name = "mauve"
value = "#ca9ee6"
[[var]]
name = "pink"
value = "#f4b8e4"
[[var]]
name = "flamingo"
value = "#eebebe"
[[var]]
name = "rosewater"
value = "#f2d5cf"
[[var]]
name = "transparent"
value = "#FF00000"
```
