### ISSUE TITLE
i3status blocks not working

### ISSUE THREAD

**Issue by mikesimps** [igor-petruk/oatbar#19]
I've read over the documents 10x and I'm not sure what I'm doing wrong. Any ideas?

Here is my output for i3status
```
$ i3status
{"version":1}
[
[{"name":"volume","instance":"default.Master.0","markup":"none","full_text":"85%"}]
,[{"name":"volume","instance":"default.Master.0","markup":"none","full_text":"85%"}]
,[{"name":"volume","instance":"default.Master.0","markup":"none","full_text":"85%"}]
```

I've tried the config two different ways, but both just show the icon on the bar (no values).
```toml
[[command]]
name="i3status"
command="i3status"

[[block]]
name="volume2"
type="text"
value="${i3status:volume.full_text}"
output_format="    ${value}"

[[block]]
name="volume"
type="number"
number_type="percent"
value="${i3status:volume.full_text}"
output_format="    ${value}"
number_display="text"
```

I confirmed that I could see an i3status process running in the background when I restart oatbar.

**Comment by igor-petruk** [comment]
Hi,

If you have `instance`, the variable is `name.instance`, not just `name`.

You can run `oatctl var ls` while the `oatber` is running and it will show the exact variable names and values you can use.

It is documented here https://oatbar.app/configuration/variable.html, but I am happy to make it somehow more discoverable

**Comment by mikesimps** [comment]
Thanks @igor-petruk for your patience and sorry for the redundant questions, I struggle when there aren't lots of examples. I got it working using oatctl var ls to find it like you suggested. Everything you've done makes a lot of sense once I get it working...just takes me a bit to pick it up.

```toml
[[var]] # set default so mute and 0% volume are handled the same
name="volume"
value="${i3status:volume.default.Master.0.full_text|def:0}"

[[block]]
name="volume"
type="number"
min_value="0"
max_value="200"
number_type="percent"
value="${volume}"
foreground="${sky}"
number_display="text"
padding=20
ramp = [
  ["0"," "],
  ["10", "    ${value}"],
  ["70", "    ${value}"],
]
```
